FROM jenkins/jenkins-master:2.265
USER root
COPY gosu-amd64 /usr/local/bin/gosu
ADD entrypoint.sh /entrypoint.sh
COPY plugins.txt /usr/share/jenkins/plugins.txt
# RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/plugins.txt

ENTRYPOINT ["/entrypoint.sh"]
